(custom-set-variables
  ;; custom-set-variables was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(Info-additional-directory-list nil)
 '(auto-compression-mode t nil (jka-compr))
 '(auto-raise-tool-bar-buttons t t)
 '(auto-resize-tool-bars t t)
 '(auto-save-default t)
 '(auto-save-directory "~/.autosave")
 '(backup-directory-alist (quote (("." . "/home/tv/.emacs-backup"))))
 '(bookmark-use-annotations t)
 '(browse-url-browser-function (quote browse-url-galeon) t)
 '(browse-url-netscape-program "run-mozilla")
 '(browse-url-netscape-version 4)
 '(browse-url-new-window-p t t)
 '(c-basic-offset 2)
 '(c-cleanup-list (quote (brace-else-brace brace-elseif-brace empty-defun-braces list-close-comma scope-operator)))
 '(c-comment-continuation-stars "* ")
 '(c-echo-syntactic-information-p t)
 '(c-hanging-colons-alist (quote ((case-label after) (label after))))
 '(c-hanging-comment-ender-p nil)
 '(c-hanging-comment-starter-p nil)
 '(c-indent-comments-syntactically-p t)
 '(cal-tex-24 t)
 '(cal-tex-diary t)
 '(calendar-date-display-form (quote ((if dayname (concat dayname ", ")) day "." month "." year)))
 '(calendar-time-display-form (quote (24-hours ":" minutes (if time-zone " (") time-zone (if time-zone ")"))))
 '(calendar-week-start-day 1)
 '(case-fold-search t)
 '(current-language-environment "UTF-8")
 '(custom-browse-sort-alphabetically nil)
 '(custom-file "/home/tv/.emacs-lib/customizations.el")
 '(cvs-allow-dir-commit t)
 '(cvs-dired-use-hook (quote always) t)
 '(cvs-edit-confirm (quote changed))
 '(cvs-edit-require-final-newline nil)
 '(cvs-parse-ignored-messages (quote ("Executing ssh-askpass to query the password.*$" ".*Remote host denied X11 forwarding.*$" "^Mailing twisted-commits\\.\\.\\.$" "^Generating notification message\\.\\.\\.$" "^Generating notification message\\.\\.\\. done\\.$")))
 '(cvs-reuse-cvs-buffer (quote samedir))
 '(default-gutter-position (quote top))
 '(default-input-method "latin-1-prefix")
 '(delete-key-deletes-forward t)
 '(diary-file "~/.diary")
 '(efs-auto-save 1 t)
 '(efs-ftp-program-args (quote ("-v")))
 '(efs-ftp-program-name "sftp")
 '(efs-ftp-prompt-regexp "^\\(s?ftp\\|Ftp\\|FTP\\)> *")
 '(efs-remote-shell-file-name "ssh")
 '(efs-remote-shell-takes-user t)
 '(efs-use-remote-shell-internally t)
 '(erc-auto-query t)
 '(erc-email-userid "tv")
 '(erc-filling t)
 '(erc-highlight-strings (quote ("[tT][vV]" "[tT]ommi" "[vV]irtanen" "utu.fi")))
 '(erc-input-hook (quote ((lambda (&optional foo bar) (set-buffer-modified-p nil)))))
 '(erc-insert-hook (quote (erc-truncate-buffer erc-fill auto-set-fill-column (lambda (&optional foo bar) (set-buffer-modified-p nil)))))
 '(erc-join-buffer (quote buffer))
 '(erc-join-info-buffer (quote disable))
 '(erc-kill-buffer-on-part t)
 '(erc-log-channels t)
 '(erc-log-channels-directory "/home/tv/data/irc/log")
 '(erc-minibuffer-notice nil)
 '(erc-nick (quote ("Tv" "Tv_" "Tv__" "Tv___" "Tv____" "Tv_____")))
 '(erc-notice-highlight-type (quote prefix))
 '(erc-pals (quote ("liiwi" "part" "liw" "moshez" "ltm" "|LTM|" "glyph")))
 '(erc-paranoid t)
 '(erc-port "ircd")
 '(erc-prompt "Tv>")
 '(erc-prompt-for-password nil)
 '(erc-prompt-interactive-input nil)
 '(erc-save-buffer-on-part t)
 '(erc-server "irc.eu.openprojects.net")
 '(eudc-default-return-attributes (quote all))
 '(eudc-strict-return-matches nil)
 '(european-calendar-style t)
 '(find-grep-options "-q" t)
 '(flyspell-mode-line-string " Fly" t)
 '(font-lock-global-modes t)
 '(font-menu-ignore-scaled-fonts nil)
 '(font-menu-this-frame-only-p t)
 '(global-font-lock-mode t nil (font-lock))
 '(gnus-article-display-hook (quote (gnus-article-display-x-face gnus-article-hide-headers-if-wanted gnus-article-hide-boring-headers gnus-article-treat-overstrike gnus-article-maybe-highlight gnus-article-display-x-face)))
 '(gnus-break-pages nil)
 '(gnus-load-hook nil)
 '(gnus-message-archive-group "nnimap+hq:INBOX.sent")
 '(gnus-secondary-select-methods (quote ((nnimap "hq" (nnimap-address "hq.yok.utu.fi") (nnimap-expunge-on-close (quote never)) (nnimap-authinfo-file "~/.imap-password") (nnimap-stream ssl)))))
 '(gnus-select-method (quote (nntp "news.utu.fi")))
 '(gnus-startup-hook (quote ((lambda nil (load-library "gnus-BTS")) gnus-topic-mode)))
 '(gnus-total-expirable-newsgroups "^nnimap\\\\+hq:INBOX\\\\.toursst\\\\.")
 '(gnuserv-init-hook nil)
 '(grep-command "grapple ")
 '(gutter-buffers-tab-visible-p nil)
 '(indent-tabs-mode t)
 '(indicate-empty-lines t)
 '(ispell-program-name "aspell")
 '(ldap-host-parameters-alist (quote (("db.debian.org" base "dc=Debian,dc=org"))))
 '(mark-diary-entries-in-calendar t)
 '(menu-bar-mode nil)
 '(modeline-3d-p t)
 '(mouse-yank-at-point t)
 '(mwheel-follow-mouse t)
 '(nnmail-spool-file "/var/spool/mail/tv")
 '(nxml-bind-meta-tab-to-complete-flag t)
 '(nxml-slash-auto-complete-flag t)
 '(paren-mode (quote paren) nil (paren))
 '(planner-ignored-from-addresses "tv@inoi\\.fi")
 '(ps-paper-type (quote a4) t)
 '(py-jpython-command "ipython")
 '(py-jpython-command-args (quote ("-noreadline -i")))
 '(py-python-command "python")
 '(require-final-newline t)
 '(rng-schema-locating-files (quote ("schemas.xml" "/home/tv/.emacs-lib/nxml-schemas.xml" "/usr/share/emacs/site-lisp/nxml-mode/schema/schemas.xml")))
 '(save-place t nil (saveplace))
 '(save-place-limit 100)
 '(scrollbars-visible-p t)
 '(shifted-motion-keys-select-region nil)
 '(show-paren-mode t nil (paren))
 '(show-trailing-whitespace t)
 '(smiley-regexp-alist (quote (("\\(\\^_\\^;;;\\)\\W" 1 "WideFaceAse3.xbm") ("\\(\\^_\\^;;\\)\\W" 1 "WideFaceAse2.xbm") ("\\(\\^_\\^;\\)\\W" 1 "WideFaceAse1.xbm") ("\\(\\^_\\^\\)\\W" 1 "WideFaceSmile.xbm") ("\\(;_;\\)\\W" 1 "WideFaceWeep.xbm") ("\\(T_T\\)\\W" 1 "WideFaceWeep.xbm") ("\\(:-*[<«]+\\)\\W" 1 "FaceAngry.xpm") ("\\(:-+\\]+\\)\\W" 1 "FaceGoofy.xpm") ("\\(:-*D\\)\\W" 1 "FaceGrinning.xpm") ("\\(:-*[)>}»]+\\)\\W" 1 "FaceHappy.xpm") ("\\(=[)»]+\\)\\W" 1 "FaceHappy.xpm") ("\\(:-*[/\\\"]\\)[^/]\\W" 1 "FaceIronic.xpm") ("[^.0-9]\\([8|]-[|Oo%]\\)\\W" 1 "FaceKOed.xpm") ("\\([:|]-*#+\\)\\W" 1 "FaceNyah.xpm") ("\\(:-*[({]+\\)\\W" 1 "FaceSad.xpm") ("\\(=[({]+\\)\\W" 1 "FaceSad.xpm") ("\\(:-*[Oo*]\\)\\W" 1 "FaceStartled.xpm") ("\\(:-*|\\)\\W" 1 "FaceStraight.xpm") ("\\(:-*p\\)\\W" 1 "FaceTalking.xpm") ("\\(:-*d\\)\\W" 1 "FaceTasty.xpm") ("\\(;-*[>)}»]+\\)\\W" 1 "FaceWinking.xpm") ("\\(:-*[Vvµ]\\)\\W" 1 "FaceWry.xpm") ("\\([:|]-*P\\)\\W" 1 "FaceYukky.xpm"))))
 '(strokes-mode t nil (strokes))
 '(strokes-use-strokes-buffer nil)
 '(tool-bar-button-margin 1 t)
 '(tool-bar-mode nil nil (tool-bar))
 '(toolbar-mail-reader (quote mutt))
 '(toolbar-visible-p nil)
 '(tramp-default-method "scp")
 '(transient-mark-mode t)
 '(uniquify-buffer-name-style (quote post-forward) nil (uniquify))
 '(url-be-asynchronous t)
 '(url-cookie-confirmation t)
 '(url-honor-refresh-requests (quote t))
 '(url-keep-history t)
 '(url-news-server "news.utu.fi")
 '(url-privacy-level (quote paranoid))
 '(url-proxy-services (quote (("http" . "hq.yok.utu.fi:5865"))))
 '(url-temporary-directory "~/tmp")
 '(view-diary-entries-initially t)
 '(w3-debug-html (quote style))
 '(w3-default-homepage "http://hq.yok.utu.fi/daily.html")
 '(w3-default-stylesheet (quote nil))
 '(w3-delay-image-loads (quote nil))
 '(w3-do-incremental-display t)
 '(w3-honor-stylesheets (quote t))
 '(w3-image-mappings (quote (("image/x-xbitmap" . xbm) ("image/xbitmap" . xbm) ("image/xbm" . xbm) ("image/jpeg" . jpeg) ("image/gif" . gif) ("image/png" . png) ("image/x-fax" . g3fax) ("image/x-raster" . rast) ("image/windowdump" . xwd) ("image/x-icon" . icon) ("image/portable-graymap" . pgm) ("image/portable-pixmap" . ppm) ("image/x-pixmap" . xpm) ("image/x-xpixmap" . xpm) ("image/pict" . pict) ("image/x-rgb" . sgi) ("image/x-sgi" . sgi) ("image/x-macpaint" . macpt) ("image/x-targa" . tga) ("image/tiff" . tiff))))
 '(w3-load-hook (quote nil) t)
 '(w3-mode-hook (quote nil))
 '(w3-netscape-compatible-comments nil)
 '(w3-preferences-cancel-hook (quote nil) t)
 '(w3-preferences-default-hook (quote nil) t)
 '(w3-preferences-ok-hook (quote nil) t)
 '(w3-preferences-setup-hook (quote nil) t)
 '(w3-source-file-hook (quote nil))
 '(w3-temporary-directory "~/tmp")
 '(w3-toolbar-orientation (quote default) t)
 '(w3-toolbar-type (quote both) t)
 '(w3-use-menus (quote (file edit view go bookmark options buffers style emacs nil help)))
 '(w3-user-colors-take-precedence (quote nil)))
(custom-set-faces
  ;; custom-set-faces was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 )
