(require 'python)
(add-hook 'python-mode-hook
  #'(lambda ()
      (define-key python-mode-map "\C-m" 'newline-and-indent)
      (define-key python-mode-map (kbd "C-c C-;") 'python-indent-shift-left)
      (define-key python-mode-map (kbd "C-c C-:") 'python-indent-shift-right)
      (define-key python-mode-map (kbd "C-c C-c") 'comment-region)
      (define-key python-mode-map (kbd "C-c C-u") 'uncomment-region)
      (define-key python-mode-map (kbd "C-c C-n") 'flycheck-next-error)
      (define-key python-mode-map (kbd "C-c C-p") 'flycheck-previous-error)
      (local-set-key "\C-ca" 'nosetests-all)
      (local-set-key "\C-cm" 'nosetests-module)
      (local-set-key "\C-c." 'nosetests-one)
      (local-set-key "\C-cpa" 'nosetests-pdb-all)
      (local-set-key "\C-cpm" 'nosetests-pdb-module)
      (local-set-key "\C-cp." 'nosetests-pdb-one)
      (subword-mode)
      (jedi:setup)
      ))
(add-hook 'flycheck-mode-hook
          #'(lambda ()
              (setq flycheck-flake8-maximum-line-length 120)))

